In [41]:
import numpy as np
import random

#1. Create a vector with values ranging from 10 to 49.

arr = np.arange(10,50,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [42]:
#2.Create a 3x3 matrix with values ranging from 0 to 8.

arr2 = np.ndarray([3,3])

for i in range(3):
    for j in range(3):
        arr2[i,j] = random.randint(1,9)
print(arr2)

[[3. 3. 7.]
 [5. 1. 7.]
 [2. 5. 1.]]


In [43]:
#3. Create a 3x3 identity matrix.

arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
# 4. Create a 3x3x3 array with random values.

arr4 = np.ndarray([3,3,3])

for i in range(3):
    for j in range(3):
        for k in range(3):
          arr4[i,j] = random.randint(1,100)
print(arr4)


[[[18. 18. 18.]
  [80. 80. 80.]
  [47. 47. 47.]]

 [[86. 86. 86.]
  [64. 64. 64.]
  [11. 11. 11.]]

 [[13. 13. 13.]
  [93. 93. 93.]
  [39. 39. 39.]]]


In [45]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.


arr5 = np.ndarray([10,10])
max_el = min_el = 0
for i in range(10):
    for j in range(10):
        arr5[i,j] = random.randint(10,1000)
        if arr5[i,j] > max_el:
            max_el = arr5[i,j]
        if arr5[i,j] < min_el:
            min_el = arr5[i,j]
print(max_el, min_el)
print(arr5)

988.0 0
[[927. 982. 862.  53. 388. 333.  14. 943.  87. 881.]
 [677. 908. 786. 751. 643. 378. 812. 716. 416.  38.]
 [137. 801. 983. 431. 643. 323. 524. 475. 857. 988.]
 [161. 871. 974. 853. 593. 570. 163. 174. 572. 131.]
 [105. 957. 567. 654. 771. 111. 314. 655. 205.  67.]
 [762.  69. 130. 416. 176. 874. 514. 842. 632. 402.]
 [870. 384. 859. 241. 595. 926. 888. 121. 592.  24.]
 [ 75. 329. 131. 645. 566. 301. 671. 849. 140. 396.]
 [874. 265. 144. 967. 898.  56. 573. 961. 468. 176.]
 [255.  47. 728. 205. 637. 322. 499.  17. 787. 881.]]


In [46]:
#6 Create a random vector of size 30 and find the mean value.
vect = np.random.rand(30)
print(vect)
print(f"mean value of vector is : {vect.mean()}")

[0.03337995 0.47113311 0.9038019  0.56969011 0.31037921 0.29681014
 0.349123   0.40347779 0.05655981 0.16989807 0.13727041 0.90137145
 0.03125507 0.24028097 0.6080344  0.90186673 0.99874264 0.27978067
 0.25359058 0.93508446 0.8532589  0.78715264 0.84857743 0.752871
 0.20669012 0.36467986 0.61319098 0.14551857 0.51320203 0.82684392]
mean value of vector is : 0.4921171972926128


In [47]:
#7 Normalize a 5x5 random matrix.
A = np.arange(9).reshape([3,3])
A_min, A_max = A.min(), A.max()
A_normalized = (A - A_min) / (A_max - A_min)
print(A_normalized)

[[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


In [57]:
#8 Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).
arr_5_3 = np.arange(15).reshape(5,3)
arr_3_2 = np.arange(6).reshape(3,2)

print("first matrix :\n", arr_5_3)
print("second matrix :\n", arr_3_2)
print("dor product: \n", np.dot(arr_5_3, arr_3_2))


first matrix :
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
second matrix :
 [[0 1]
 [2 3]
 [4 5]]
dor product: 
 [[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [58]:
#9 Create two 3x3 matrices and compute their dot product.

arr_9_1 = np.random.randint(0, 100, (3, 3))  # Random integers from 0 to 99
arr_9_2 = np.random.rand(3, 3)  # Random floats between 0 and 1


print("first matrix :\n", arr_9_1)
print("second matrix :\n", arr_9_2)
print("dor product: \n", np.dot(arr_9_1, arr_9_2))

first matrix :
 [[31 28 16]
 [99 54 79]
 [74 52 49]]
second matrix :
 [[0.20109483 0.98126555 0.38856071]
 [0.24185231 0.09436785 0.48620779]
 [0.1498626  0.81880764 0.22445877]]
dor product: 
 [[ 15.40360616  46.16245418  29.25054044]
 [ 44.80755855 166.92695729  82.45497385]
 [ 34.8006052  117.64235351  65.03477736]]


In [62]:
#Given a 4x4 matrix, find its transpose.
arr_10 = np.random.randint(0,50, (4, 4))  # Random floats between 0 and 1
def transpose_matrix(matrix):
    tr = np.transpose(matrix)
    print("matrix :\n", matrix)
    print("transposed matrix :\n", tr)
transpose_matrix(arr_10)

matrix :
 [[37 17 44 40]
 [45  9 14 41]
 [ 8  3 10 29]
 [30 12 10  4]]
transposed matrix :
 [[37 45  8 30]
 [17  9  3 12]
 [44 14 10 10]
 [40 41 29  4]]


In [63]:
#11 Create a 3x3 matrix and calculate its determinant.

arr_11 = np.random.randint(0,50, (3, 3))  # Random floats between 0 and 1
def transpose_matrix(matrix):
    tr = np.linalg.det(matrix)
    print("matrix :\n", matrix)
    print("determinant of the  matrix :\n", tr)
transpose_matrix(arr_10)

matrix :
 [[37 17 44 40]
 [45  9 14 41]
 [ 8  3 10 29]
 [30 12 10  4]]
determinant of the  matrix :
 -143754.0000000001


In [69]:
#12 Create two matrices ( A ) (3x4) and ( B ) (4x3), and compute the matrix product ( A \cdot B ).

A = np.random.randint(0, 100, (3,4))
B = np.random.randint(0, 100, (4, 3))

# Matrix product
C = A @ B
C2 = np.matmul(A, B) # equivalent to above

print("Matrix A :", A, '\nMatrix B : ', B, "\nProduct : ", C)

Matrix A : [[42 51 83  6]
 [66 13 45 66]
 [78 30 52 44]] 
Matrix B :  [[23 86 20]
 [46 35 80]
 [43 39 70]
 [ 3 45 59]] 
Product :  [[ 6899  8904 11084]
 [ 4249 10856  9404]
 [ 5542 11766 10196]]


In [74]:
#13 Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product.
A = np.random.randint(0, 100, (3,3))
B = np.random.randint(0, 100, 3)
# Matrix product
C = A @ B
C2 = np.matmul(A, B) # equivalent to above

print("Matrix A :", A, '\nMatrix B : ', B, "\nProduct : ", C)

Matrix A : [[68 71 60]
 [25 41 94]
 [60 79 36]] 
Matrix B :  [ 2  5 30] 
Product :  [2291 3075 1595]


In [79]:
#14 Solve the linear system ( Ax = b ) where ( A ) is a 3x3 matrix, and ( b ) is a 3x1 column vector.
A = np.random.randint(0, 100, (3,3))
B = np.random.randint(0, 100, 3)
A_inv = np.linalg.inv(A)
# Matrix product
C = A_inv @ B


print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Solution x:\n", C)

Matrix A:
 [[87 19 40]
 [51 74 70]
 [33 66  0]]
Matrix B:
 [87 38 34]
Solution x:
 [ 1.11196238 -0.04082967 -0.22412408]


In [83]:
#15 Given a 5x5 matrix, find the row-wise and column-wise sums.
A = np.random.randint(0, 100, (5,5))

column_sum = np.sum(A, axis=1)
print(A)
row_sum = []
for row in A:
    row_sum.append(int(np.sum(row)))
col_sum = []
for col in np.transpose(A):
    col_sum.append(int(np.sum(col)))

print("row sums:\n", row_sum)
print("column sums:\n", col_sum)



[[91 32 82 85 63]
 [63 67  9 32 35]
 [72 79 79 36 20]
 [74 76 22 81 29]
 [52 29 47 64 34]]
row sums:
 [353, 206, 286, 282, 226]
column sums:
 [352, 283, 239, 298, 181]
