In [1]:
from PIL import Image
import numpy as np

In [2]:
with Image.open('birds.jpg') as img:
    print(img.mode)
    img_arr=np.array(img)
    print(img_arr)

RGB
[[[ 34  98   2]
  [ 34  98   2]
  [ 34  98   2]
  ...
  [ 40  75  19]
  [ 40  75  19]
  [ 40  75  19]]

 [[ 34  98   2]
  [ 34  98   2]
  [ 34  98   2]
  ...
  [ 37  72  16]
  [ 37  72  16]
  [ 37  72  16]]

 [[ 34  98   2]
  [ 34  98   2]
  [ 34  98   2]
  ...
  [ 35  70  14]
  [ 35  70  14]
  [ 35  70  14]]

 ...

 [[ 21  75   0]
  [ 21  75   0]
  [ 21  75   0]
  ...
  [144 110 111]
  [139 105 106]
  [137 103 104]]

 [[ 21  75   0]
  [ 21  75   0]
  [ 21  75   0]
  ...
  [147 113 112]
  [141 107 106]
  [138 104 103]]

 [[ 21  75   0]
  [ 21  75   0]
  [ 21  75   0]
  ...
  [151 117 116]
  [145 111 110]
  [143 109 108]]]


In [3]:
#flipped image
flip_arr=img_arr[::-1,::-1, :]
flipped_birds=Image.fromarray(flip_arr)
flipped_birds.show()
flipped_birds.save('flipped_birds.jpg')

In [4]:
uniform_noise=np.random.uniform(-30,30,img_arr.shape)
noise_array=np.clip(img_arr+uniform_noise,0,255).astype(np.uint8)
noise_img=Image.fromarray(noise_array)
noise_img.show()
noise_img.save('noise_image.jpg')

In [5]:
increase_value=30

img_arr[:,:,0]=np.clip(img_arr[:,:,0]+increase_value, 0 , 255)
brightened_img=Image.fromarray(img_arr.astype(np.uint8))
brightened_img.show()
brightened_img.save('brightened_img.jpg')

In [6]:
height,width,_=img_arr.shape
mask_size=100
start_x=(width-mask_size)//2
start_y=(height-mask_size)//2

img_arr[start_y:start_y+mask_size, start_x:start_x+mask_size]=[0,0,0]

masked_img=Image.fromarray(img_arr)

masked_img.show()
masked_img.save('Masked_image.jpg')